apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.7.19
    helm:
      values: |
        backendStore:
          databaseMigration: true
          postgres:
            enabled: true
            host: postgres-postgresql.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow
        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            awsAccessKeyId: minioadmin
            awsSecretAccessKey: minioadmin
        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: "http://minio.mlflow.svc.cluster.local:9000"
          AWS_ACCESS_KEY_ID: "minioadmin"
          AWS_SECRET_ACCESS_KEY: "minioadmin"
        service:
          type: ClusterIP
          port: 5000
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true